# Generated by Django 4.2.5 on 2023-10-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_acessomedico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcessoMedico',
        ),
    ]
